function (generate_constants_processor PREFIX PREFIX_LOWER_CASE TARGET_PATH GENERATOR_PATH)
  set (OUTPUT_CONSTANTS_LENGTH "CMAKE_CONSTANTS_LENGTH")
  set (OUTPUT_ALPHABET_LENGTH "CMAKE_ALPHABET_LENGTH")
  set (OUTPUT_SYMBOL_BY_BYTES "CMAKE_SYMBOL_BY_BYTES")
  set (OUTPUT_MAX_STATE "CMAKE_MAX_STATE")
  set (OUTPUT_MIN_STATE_BITS "CMAKE_MIN_STATE_BITS")
  set (OUTPUT_NEXT_STATE_BY_LAST_SYMBOLS "CMAKE_NEXT_STATE_BY_LAST_SYMBOLS")

  set (BINARY_DIR "${PROJECT_BINARY_DIR}/CMakeTmp/generate_constants_processor")
  set (SOURCE_DIR "${PROJECT_SOURCE_DIR}/cmake/generators/constants_processor")
  set (NAME "cmake_generate_constants_processor")

  set (MESSAGE_PREFIX "${PREFIX_LOWER_CASE} constants processor")

  try_compile (
    COMPILE_RESULT ${BINARY_DIR} ${SOURCE_DIR} ${NAME}
    CMAKE_FLAGS
      "-DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}"
      "-DTARGET_PATH=${TARGET_PATH}"
      "-DGENERATOR_PATH=${GENERATOR_PATH}"
    OUTPUT_VARIABLE COMPILE_OUTPUT
  )
  if (CMAKE_VERBOSE_MAKEFILE)
    message (STATUS ${COMPILE_OUTPUT})
  endif ()

  if (COMPILE_RESULT)
    execute_process (
      COMMAND "${BINARY_DIR}/main"
      RESULT_VARIABLE RUN_RESULT
      OUTPUT_VARIABLE RUN_OUTPUT
    )

    if (RUN_RESULT EQUAL 0)
      list (GET RUN_OUTPUT 0 CONSTANTS_LENGTH)
      set (${OUTPUT_CONSTANTS_LENGTH} ${CONSTANTS_LENGTH} PARENT_SCOPE)
      list (GET RUN_OUTPUT 1 ALPHABET_LENGTH)
      set (${OUTPUT_ALPHABET_LENGTH} ${ALPHABET_LENGTH} PARENT_SCOPE)
      list (GET RUN_OUTPUT 2 SYMBOL_BY_BYTES)
      set (${OUTPUT_SYMBOL_BY_BYTES} ${SYMBOL_BY_BYTES} PARENT_SCOPE)
      list (GET RUN_OUTPUT 3 MAX_STATE)
      set (${OUTPUT_MAX_STATE} ${MAX_STATE} PARENT_SCOPE)
      list (GET RUN_OUTPUT 4 MIN_STATE_BITS)
      set (${OUTPUT_MIN_STATE_BITS} ${MIN_STATE_BITS} PARENT_SCOPE)
      list (GET RUN_OUTPUT 5 NEXT_STATE_BY_LAST_SYMBOLS)
      set (${OUTPUT_NEXT_STATE_BY_LAST_SYMBOLS} ${NEXT_STATE_BY_LAST_SYMBOLS} PARENT_SCOPE)
      message (STATUS "${MESSAGE_PREFIX} - generated")
    else ()
      unset (${OUTPUT_CONSTANTS_LENGTH} PARENT_SCOPE)
      unset (${OUTPUT_ALPHABET_LENGTH} PARENT_SCOPE)
      unset (${OUTPUT_SYMBOL_BY_BYTES} PARENT_SCOPE)
      unset (${OUTPUT_MAX_STATE} PARENT_SCOPE)
      unset (${OUTPUT_MIN_STATE_BITS} PARENT_SCOPE)
      unset (${OUTPUT_NEXT_STATE_BY_LAST_SYMBOLS} PARENT_SCOPE)
      message (STATUS "${MESSAGE_PREFIX} - failed to generate, using default")
    endif ()
  else ()
    unset (${OUTPUT_CONSTANTS_LENGTH} PARENT_SCOPE)
    unset (${OUTPUT_ALPHABET_LENGTH} PARENT_SCOPE)
    unset (${OUTPUT_SYMBOL_BY_BYTES} PARENT_SCOPE)
    unset (${OUTPUT_MAX_STATE} PARENT_SCOPE)
    unset (${OUTPUT_MIN_STATE_BITS} PARENT_SCOPE)
    unset (${OUTPUT_NEXT_STATE_BY_LAST_SYMBOLS} PARENT_SCOPE)
    message (STATUS "${MESSAGE_PREFIX} - compilation failed, using default")
  endif ()

  FILE (REMOVE_RECURSE ${BINARY_DIR})

  mark_as_advanced (
    ${OUTPUT_CONSTANTS_LENGTH}
    ${OUTPUT_ALPHABET_LENGTH}
    ${OUTPUT_SYMBOL_BY_BYTES}
    ${OUTPUT_MAX_STATE}
    ${OUTPUT_MIN_STATE_BITS}
    ${OUTPUT_NEXT_STATE_BY_LAST_SYMBOLS}
  )
endfunction ()
