// Old generation HTTP (v0.9, v1.0, v1.1) C library.
// Copyright (c) 2019 AUTHORS, MIT License.

#if !defined(OGHTTP_PARSER_CONSTANT_H)
#define OGHTTP_PARSER_CONSTANT_H

#include "common.h"

#define OGHTTP_PARSER_CONSTANT_GENERATE_DATA(PREFIX, CONSTANT) \
  const char* OGHTTP_##PREFIX##_PARSER_CONSTANT = CONSTANT;

#define OGHTTP_PARSER_CONSTANT_GENERATE_INITIAL_STATE(PREFIX, PREFIX_LOWER_CASE) \
  const oghttp_##PREFIX_LOWER_CASE##_parser_state_fast_t OGHTTP_##PREFIX##_PARSER_INITIAL_STATE = 0;

#endif // OGHTTP_PARSER_CONSTANT_H
