// HTTP old generation (v0.9, v1.0, v1.1) C library.
// Copyright (c) 2019 AUTHORS, MIT License.

// This file was generated, do not edit manually.
// This file is intended to be used by generator only.

// It may not be possible to run generator while cross compiling.
// So generated file should be shipped with its template.

#include "options.h"

const char* HOG_CONSTANTS[] = {
  "Continue",
  "Switching Protocols",
  "Processing",
  "Early Hints",
  "Unassigned",
  "OK",
  "Created",
  "Accepted",
  "Non-Authoritative Information",
  "No Content",
  "Reset Content",
  "Partial Content",
  "Multi-Status",
  "Already Reported",
  "Unassigned",
  "IM Used",
  "Unassigned",
  "Multiple Choices",
  "Moved Permanently",
  "Found",
  "See Other",
  "Not Modified",
  "Use Proxy",
  "(Unused)",
  "Temporary Redirect",
  "Permanent Redirect",
  "Unassigned",
  "Bad Request",
  "Unauthorized",
  "Payment Required",
  "Forbidden",
  "Not Found",
  "Method Not Allowed",
  "Not Acceptable",
  "Proxy Authentication Required",
  "Request Timeout",
  "Conflict",
  "Gone",
  "Length Required",
  "Precondition Failed",
  "Payload Too Large",
  "URI Too Long",
  "Unsupported Media Type",
  "Range Not Satisfiable",
  "Expectation Failed",
  "Unassigned",
  "Misdirected Request",
  "Unprocessable Entity",
  "Locked",
  "Failed Dependency",
  "Too Early",
  "Upgrade Required",
  "Unassigned",
  "Precondition Required",
  "Too Many Requests",
  "Unassigned",
  "Request Header Fields Too Large",
  "Unassigned",
  "Unavailable For Legal Reasons",
  "Unassigned",
  "Internal Server Error",
  "Not Implemented",
  "Bad Gateway",
  "Service Unavailable",
  "Gateway Timeout",
  "HTTP Version Not Supported",
  "Variant Also Negotiates",
  "Insufficient Storage",
  "Loop Detected",
  "Unassigned",
  "Not Extended",
  "Network Authentication Required",
  "Unassigned"};

const size_t HOG_CONSTANTS_LENGTH = sizeof(HOG_CONSTANTS) / sizeof(HOG_CONSTANTS[0]);
