// Old generation HTTP (v0.9, v1.0, v1.1) C library.
// Copyright (c) 2019 AUTHORS, MIT License.

// This file was generated, do not edit manually.
// This file is intended to be used by generator only.

// It may not be possible to run generator while cross compiling.
// So generated file should be distributed with its template.

#include "options.h"

const char* OGH_CONSTANTS[] = {"Continue",
                               "Switching Protocols",
                               "Processing",
                               "Early Hints",
                               "OK",
                               "Created",
                               "Accepted",
                               "Non-Authoritative Information",
                               "No Content",
                               "Reset Content",
                               "Partial Content",
                               "Multi-Status",
                               "Already Reported",
                               "IM Used",
                               "Multiple Choices",
                               "Moved Permanently",
                               "Found",
                               "See Other",
                               "Not Modified",
                               "Use Proxy",
                               "(Unused)",
                               "Temporary Redirect",
                               "Permanent Redirect",
                               "Bad Request",
                               "Unauthorized",
                               "Payment Required",
                               "Forbidden",
                               "Not Found",
                               "Method Not Allowed",
                               "Not Acceptable",
                               "Proxy Authentication Required",
                               "Request Timeout",
                               "Conflict",
                               "Gone",
                               "Length Required",
                               "Precondition Failed",
                               "Payload Too Large",
                               "URI Too Long",
                               "Unsupported Media Type",
                               "Range Not Satisfiable",
                               "Expectation Failed",
                               "Misdirected Request",
                               "Unprocessable Entity",
                               "Locked",
                               "Failed Dependency",
                               "Too Early",
                               "Upgrade Required",
                               "Precondition Required",
                               "Too Many Requests",
                               "Request Header Fields Too Large",
                               "Unavailable For Legal Reasons",
                               "Internal Server Error",
                               "Not Implemented",
                               "Bad Gateway",
                               "Service Unavailable",
                               "Gateway Timeout",
                               "HTTP Version Not Supported",
                               "Variant Also Negotiates",
                               "Insufficient Storage",
                               "Loop Detected",
                               "Not Extended",
                               "Network Authentication Required",
                               "Response is Stale",
                               "Revalidation Failed",
                               "Disconnected Operation",
                               "Heuristic Expiration",
                               "Miscellaneous Warning",
                               "Transformation Applied",
                               "Miscellaneous Persistent Warning"};

const size_t OGH_CONSTANTS_LENGTH = sizeof(OGH_CONSTANTS) / sizeof(OGH_CONSTANTS[0]);
